myparcelnl/delivery-options

src/assets/scss/delivery-options/style.scss
src/delivery-options/components/CButton.vue
src/delivery-options/components/Pickup/Pickup.vue

| Before | After |
|--------|------|
| ![localhost_8080_ (1)](https://user-images.githubusercontent.com/3886637/88897993-70339e80-d24c-11ea-97d4-683d1b776a27.png) | ![localhost_8080_](https://user-images.githubusercontent.com/3886637/88897995-7164cb80-d24c-11ea-9bb3-461aad706ad0.png) |

Add spacing around pickup location buttons

---

src/delivery-options/data/delivery/getDeliveryDates.js

fix: invalid date in safari when selecting delivery date (#9)

---

.huskyrc.js
private/config-variables.js
private/delivery-options.config.js

* Fix "banner" comment in built files
* Remove husky pre-push hook for running tests. It's run on opening a PR and must pass before it can be merged anyway.

Build changes

---

src/delivery-options/DeliveryOptions.vue

Fix not being able to re-show the delivery options after calling the `hide` function.
Fixes myparcelnl/woocommerce#336
Fixes myparcelbe/woocommerce#130

Fix showing and hiding

---

src/delivery-options/components/RecursiveForm/RecursiveForm.vue
src/delivery-options/data/pickup/createPickupChoices.js
src/delivery-options/data/pickup/fetchPickupLocations.js

fix: error and broken map on getting pickup locations for invalid address

---

src/data/defaultAddress.js
src/delivery-options/data/delivery/createDeliveryDependencies.js
src/delivery-options/data/delivery/createDeliveryOptions.js
src/delivery-options/data/delivery/getDeliveryOptions.js
tests/.eslintrc
tests/__mocks__/@myparcel/js-sdk/dist/data/delivery-options/getDeliveryOptionsEntry.js
tests/unit/delivery-options/deliveryMoment.spec.js

fix: show delivery moments in the correct order

---

src/delivery-options/components/Pickup/Map/Leaflet.vue

fix: always show at least a few markers on the map

---

README.md
src/data/keys/configKeys.js
src/delivery-options/config/configBus.js
src/delivery-options/config/hasFilterableValue.js
src/delivery-options/config/settingHasCarrierOverride.js
src/delivery-options/config/settingHasCountryOverride.js
src/sandbox/sandboxConfigBus.js
tests/unit/delivery-options/configBus.spec.js
types/index.d.ts

- currently only possible for pickup and delivery
- Resolves #4

feat: allow country overrides in settings

---

src/config/localeConfig.js
src/delivery-options/DeliveryOptions.vue
src/delivery-options/components/Errors.vue
src/delivery-options/data/request/getDefaultRequestParameters.js

feat: allow use of street instead of number

---

src/delivery-options/data/pickup/getPickupLocations.js

feat: don't show pickup when package type is not package

---

src/sandbox/components/CCodeDisplay.vue
yarn.lock

- fixes 2 critical and 6 moderate vulnerabilities
- remove highlight deprecation notice on sandbox

chore: update dependencies

---

src/data/carriers/abstractCarrierConfiguration.js
src/data/carriers/upsCarrierConfiguration.js
tests/unit/delivery-options/__snapshots__/carrierConfigurationFactory.spec.js.snap
tests/unit/delivery-options/carrierConfigurationFactory.spec.js

feat: add blacklist for delivery countries

---

src/data/carriers/dpdCarrierConfiguration.js
tests/unit/delivery-options/__snapshots__/carrierConfigurationFactory.spec.js.snap

feat(dpd): add netherlands for pickup

---

src/config/extraDeliveryConfig.js
src/data/keys/configKeys.js
src/delivery-options/data/request/getExtraDropOffDay.js
src/sandbox/settings/form.js
src/sandbox/translations/en.js
tests/unit/delivery-options/delivery/dropOffDays.spec.js

feat: add sunday cutoff time

---

src/data/carriers/postNlCarrierConfiguration.js
tests/unit/delivery-options/__snapshots__/carrierConfigurationFactory.spec.js.snap

feat: add pudo countries for postnl

---

libs/shared/src/config/getMyParcelConfig.ts
libs/shared/src/utils/__snapshots__/getPlatformConfig.spec.ts.snap

feat: add mailbox to dpd

---

apps/delivery-options/src/__tests__/utils/mockSelectedDeliveryOptions.ts
apps/delivery-options/src/composables/useResolvedPickupLocations.ts
apps/sandbox/src/composables/useAddressSelector.ts

fix(pickup): fix map markers not reloading properly on address change

---

src/data/carriers/abstractCarrierConfiguration.js
tests/unit/delivery-options/carrierConfiguration.spec.js

feat: allow small parcel to be sent to belgium

---

apps/delivery-options/src/composables/events/useResolvedValues.spec.ts
apps/delivery-options/src/composables/events/useResolvedValues.ts
apps/delivery-options/src/types/form.types.ts
libs/shared/src/types/config.types.ts

fix: don't output false for shipment options that are disabled

---

apps/delivery-options/src/composables/events/useResolvedValues.ts
apps/delivery-options/src/composables/useResolvedCarrier.ts
apps/delivery-options/src/composables/useResolvedPickupLocations.ts
apps/delivery-options/src/main.spec.ts
apps/delivery-options/src/utils/getHasPickupForPackage.ts
apps/delivery-options/src/utils/getResolvedCarrier.spec.ts
apps/delivery-options/src/utils/getResolvedCarrier.ts
apps/delivery-options/src/views/MyParcelDeliveryOptions/DeliveryOptionsForm/DeliveryOptionsForm.vue
libs/shared/src/composables/useCarrier.spec.ts
libs/shared/src/composables/useCarrier.ts
libs/shared/src/config/getMyParcelConfig.ts
libs/shared/src/data/settingsConsts.ts
libs/shared/src/types/platform.types.ts
libs/shared/src/utils/__snapshots__/getPlatformConfig.spec.ts.snap

feat: klein pakket belgie pickup

---

apps/delivery-options/src/utils/getResolvedCarrier.spec.ts
libs/shared/src/config/getMyParcelConfig.ts
libs/shared/src/utils/__snapshots__/getPlatformConfig.spec.ts.snap

feat: support dhlforyou pickup locations correctly

---

apps/delivery-options/src/utils/stringToDate.ts

fix: align timezone with actual delivery times

---

.github/dependabot.yml
.github/workflows/release.yml

ci: manage dependencies using dependabot and automatically purge cdn caches on release

---

apps/delivery-options/src/components/map/LeafletMapInner/LeafletMapInner.vue

fixes an error where the Leaflet script might not be loaded from the CDN before the map was initialized
fixes INT-857

fix: fix an error when attempting to open pickup locations map

---

apps/delivery-options/package.json
apps/delivery-options/vite.config.ts

feat: provide a build without vue

---

.eslintrc.cjs
apps/delivery-options/src/components/map/LeafletMapInner/LeafletMapInner.vue
apps/delivery-options/src/components/map/LeafletMarker/LeafletMarker.vue
apps/delivery-options/src/composables/usePickupLocationsMap.ts
apps/delivery-options/src/types/map.types.ts
apps/delivery-options/src/views/MyParcelDeliveryOptions/Pickup/PickupLocationMapMarker/PickupLocationMapMarker.vue

fix: use an external version of leaflet if already loaded

---

apps/delivery-options/src/components/common/PriceTag/PriceTag.vue
apps/delivery-options/src/components/form/GroupInput/GroupInput.vue
apps/delivery-options/src/config/__snapshots__/getDefaultConfigForPlatform.spec.ts.snap
apps/sandbox/src/components/SandboxFeaturesBox.vue
libs/shared/src/data/enums.ts
libs/shared/src/data/getDefaultDeliveryOptionsConfig.ts
libs/shared/src/types/config.types.ts
libs/shared/src/utils/getAllConfigOptions.ts

feat: allow showing '0' prices as "free"

---

apps/delivery-options/src/composables/useDateFormat.spec.ts
apps/delivery-options/src/composables/useDateFormat.ts
apps/delivery-options/src/views/MyParcelDeliveryOptions/Delivery/DeliveryDateSelector/DateBlock.vue
apps/delivery-options/src/views/MyParcelDeliveryOptions/Pickup/PickupLocationOpeningHours/PickupLocationOpeningHours.vue

feat: translate pickup location weekdays based on locale

---

apps/sandbox/package.json
yarn.lock

feat: change translation importer package
